class BTYPE:
	Grass = 'grassCube.png'
	GrassModel = 'GrassCube.obj'
	Brick = 'brick.png'
	Sand = 'sand.png'
	Log = 'log.png'
	Craft = 'crafting table Tex.png'
	Smelt = 'furnace.png'
	leaves = 'leaves.png'
	MossyCobble = 'mossy cobblestoneTex'